[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[build]
  publish = "build"
  command = "yarn build" 

[build.environment]
  NODE_VERSION = "lts/*"
